### ISSUE TITLE
Problem in environment with multiple SCOM management servers

### ISSUE THREAD

**Issue by ThorstenS0069** [Juanito99/SolarWinds_NPM_OpsMgr#2]
Hi,

First of all thank you for all the work. That was a great help to get me going.

I've downloaded your code and adapted it to our needs. We had to use the table Orion.Nodes to get all devices. I also changed the code to use a RunAs profile to pass the credentials for Orion into the PowerShell script so that it won't be exposed in the registry 

So far it works good in our dev environment which has only got one SCOM management server. When importing that into an environment with multiple MPs I see a couple of isses:
Discovery works ok, but monitoring only updates the status on some of the devices. We have five management servers and only 20% of the devices are monitored. Also, the MP only works when the watcher node is on a management server. Using a normal member server does not even start to discover the devices. 
Do you know what the problem could be ? To me it looks like the monitoring is running on all management servers instead on only one. Since only one has the entries in the registry only a portion of the devices report the correct status. 

Thanks a lot and keep up the good work !

Thorsten

**Comment by thorsten-schneider-nwl** [comment]
I think that behaviour is because the classes are unhosted. I was able to fix that by hosting the nodes class
